version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file: ./environments/dev.env
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-pguser}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-pgpassword}'
      POSTGRES_DB: '${POSTGRES_DB:-forum-app}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
